application: helsinki-weather-radars
version: 1
runtime: python39
api_version: 1
threadsafe: true

#default_expiration: "30d"

handlers:
- url: /static
  static_dir: static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
