application: helsinki-weather-radars
version: 1
runtime: python39
api_version: 1
threadsafe: true

#default_expiration: "30d"

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /(.*\.appcache)
  mime_type: text/cache-manifest
  static_files: static/\1
  upload: static/(.*\.appcache)
  expiration: "0"

- url: /static
  static_dir: static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
